### ISSUE TITLE
taxvat vs vat_id

### ISSUE THREAD

**Issue by adrianojfg** [webjump/magento2-module-braspagpagador#67]
Estamos realizando testes na loja Magento 2, utilizando este módulo na última versão atual (3.7.27). Notamos que ao gerar um boleto, a informação de CPF/CNPJ vem de um campo chamado "vat_id", que pode ser configurado para aparecer ou não na loja, pois é um campo de CPF/CNPJ vinculado ao endereço de entrega/cobrança. Como não vamos habilitar este campo, o ideal seria o módulo coletar o campo chamado "taxvat", que é o CPF/CNPJ vinculado ao consumidor, porém isso não acontece e o boleto fica com o campo CPF/CNPJ em branco.

Tem alguma configuração para isso ou alguma outra forma de resolver?

**Comment by rodrigowebjump** [comment]
Olá Adriano,

Esse campo pode ser configurado em Sales -> Payment Methods -> Webjump Braspag -> Customer Config -> Address -> Customer Identity (CPF/CNPJ) Attribute.

Lembrando que o campo taxvat no pedido é salvo como customer_taxvat.

**Comment by adrianojfg** [comment]
Obrigado, Rodrigo. Estava tentando apenas taxvat.
