### ISSUE TITLE
Erro na instalação - Magento 2.3

### ISSUE THREAD

**Issue by edurodriguesdias** [webjump/magento2-module-braspagpagador#69]
Estou tentando instalar o módulo num e-commerce Magento 2.3, porém obtenho o seguinte erro: 

> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento_2.core_config_data' doesn't exist, query was: UPDATE core_config_data SET value = replace(value,'Redecard','Rede') WHERE path like '%payment/braspag_pagador%' and value like '%Redecard%';

A tabela "core_config_data" existe, mas quando fiz a instalção inseri um prefixo padrão para tabelas (nesse caso deveria ser "mg2_core_config_data"). A query acima não considera essa prefixo ao tentar fazer o update.

**Comment by jonatasavila** [comment]
Boa tarde @edurodriguesdias.

Obrigado pelo seu contato. Iremos analisar o problema reportado.
Pedimos que aguarde 24 hrs para o feedback a respeito da ação que será tomada.

**Comment by jonataswebjump** [comment]
Boa tarde @edurodriguesdias.

Obrigado pelo seu contato. Iremos analisar o problema reportado.
Pedimos que aguarde 24 hrs para o feedback a respeito da ação que será tomada.

**Comment by jonataswebjump** [comment]
@edurodriguesdias.
Identificamos o problema e de fato é um bug.
O prazo para resolvermos é até o dia 03/06.

**Comment by jonataswebjump** [comment]
Resolvido na issue #70.
