### ISSUE TITLE
Swagger apresentando erro interno após instalação do módulo

### ISSUE THREAD

**Issue by donnes** [webjump/magento2-module-braspagpagador#82]
Após instalar o módulo Webjump Braspag não é possível acessar o Swagger com a documentação das APIs.

```
The "array" class doesn't exist and the namespace must be specified. Verify and try again.
```

### Environment
Magento 2.3

### Steps to reproduce
Instalar módulo Braspag conforme documentação.

### Expected result
Abrir Swagger com os serviços

### Actual result
![image](https://user-images.githubusercontent.com/9506146/63879804-cb0ca800-c9a2-11e9-8ec3-2f6a1c1098f9.png)

**Comment by donnes** [comment]
Nenhuma novidade @jonataswebjump ?

**Comment by marcelo011982** [comment]
@jonataswebjump  tb tive o erro. Buscando na net algumas fontes falaram para trocar , no caminho
vendor/webjump/magento2-module-braspagpagador/Api/Auth3Ds20TokenManagerInterface.php
o return array
para 
return mixed.
O return array , quando chega em :
vendor/magento/framework/Reflection/TypeProcessor.php
Na linha:
" if (!$this->isTypeSimple($typeName) && !$this->isTypeAny($typeName)) {"
Ele entra e joga uma exceção.

**Comment by jonataswebjump** [comment]
Ok, priorizaremos essa demanda.

**Comment by jonatasavila** [comment]
https://github.com/webjump/magento2-module-braspagpagador/pull/91
