### ISSUE TITLE
Erro Magento 2.3.2

### ISSUE THREAD

**Issue by netobasilio** [webjump/magento2-module-braspagpagador#84]
Foi removido o comentário no método paymentStatusChanged  na
interface NotificationManagerInterface.

Assim ao executar o setup:upgrade recebemos uma mensagem de erro:

Each method must have a doc block. See Webjump\BraspagPagador\Api\NotificationManagerInterface::paymentStatusChanged()

Solução: Voltar o comentário no método 
    /**
     * @param string $paymentId
     * @return boolean
     */
    public function paymentStatusChanged(string $paymentId);

**Comment by donnes** [comment]
Correção temporária é forçar a versão `3.8.5` no `composer.json`

**Comment by jonataswebjump** [comment]
Criado a PR com o fix.
https://github.com/webjump/magento2-module-braspagpagador/pull/85
