### ISSUE TITLE
Erro ao instalar o módulo via composer

### ISSUE THREAD

**Issue by wurthmann** [webjump/magento2-module-braspagpagador#87]
Ao tentar instalar o módulo via composer o mesmo retorna a seguinte mensagem:

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install webjump/magento2-module-braspagpagador 3.8.7
    - Conclusion: don't install webjump/magento2-module-braspagpagador 3.8.6
    - Conclusion: don't install webjump/magento2-module-braspagpagador 3.8.5
    - Conclusion: don't install webjump/magento2-module-braspagpagador 3.8.4
    - Conclusion: don't install webjump/magento2-module-braspagpagador 3.8.3
    - Conclusion: don't install webjump/magento2-module-braspagpagador 3.8.2
    - Conclusion: don't install webjump/magento2-module-braspagpagador 3.8.1
    - Conclusion: remove zendframework/zend-stdlib 2.4.11
    - Installation request for webjump/magento2-module-braspagpagador ^3.8 -> satisfiable by webjump/magento2-module-braspagpagador[3.8.0, 3.8.1, 3.8.2, 3.8.3, 3.8.4, 3.8.5, 3.8.6, 3.8.7].
    - Conclusion: don't install zendframework/zend-stdlib 2.4.11
    - webjump/magento2-module-braspagpagador 3.8.0 requires zendframework/zend-stdlib 2.4.6|~2.7.7 -> satisfiable by zendframework/zend-stdlib[2.4.6, 2.7.7].
    - Can only install one of: zendframework/zend-stdlib[2.4.6, 2.4.11].
    - Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.11].
    - Installation request for zendframework/zend-stdlib (locked at 2.4.11) -> satisfiable by zendframework/zend-stdlib[2.4.11].

Installation failed, reverting ./composer.json to its original content.
`

Alguém saberia me dizer o que fazer para resolver, procurei por soluções na internet e não achei, atualmente minha loja utiliza o Magento 2.1.7

**Comment by jonataswebjump** [comment]
Problema do zend-stdlib resolvido na PR:
https://github.com/webjump/magento2-module-braspagpagador/pull/91

**Comment by diegocpires** [comment]
@wurthmann 

Qual comando você está utilizando para atualizar o magento para o 2.3.3?

Fizemos alguns testes aqui e funcionou corretamente.

**Comment by diegocpires** [comment]
@wurthmann Algum retorno?

**Comment by wurthmann** [comment]
Então não estou atualizando o Magento, pois o tema que utilizo funciona
apenas na versão 2.1.7 ... Acabei encontrando uma solução instalando a
versão 3.4 do módulo Braspag aparentemente funcionando... Mas se tento
instalar a versão atual do módulo de vocês sigo com o mesmo erro

Em ter, 26 de nov de 2019 10:45, Diego Pires <notifications@github.com>
escreveu:
